[env:genericSTM32F405RG]
platform = ststm32
board = genericSTM32F405RG
framework = stm32cube

upload_protocol = stlink
monitor_speed = 115200

build_flags =
    -DSTM32F405xx
    -DUSE_HAL_DRIVER
    -DHARDWARE_BUILD
    -I.
    -Icore
    -Idevices
    -Iplatform
    -Istm32

build_src_filter =
    -<*>
    +<../stm32/*.c>
    +<../stm32/*.cpp>
    +<../core/*.cpp>
    +<../devices/sequencer/*.cpp>
    +<../devices/sequencer/chords/*.cpp>
    +<../platform/midi/*.cpp>
