[platformio]
default_envs = genericSTM32F405RG

[env:genericSTM32F405RG]
platform = ststm32
board = genericSTM32F405RG
framework = stm32cube

upload_protocol = stlink
debug_tool = stlink
build_type = debug
build_unflags = -Os -O1 -O2 -O3
monitor_speed = 115200

build_flags =
     -O2
    -DSTM32F405xx
    -DUSE_HAL_DRIVER
    -DHARDWARE_BUILD
    -DST7789_ROTATION=3
    -DLCD_USE_18BIT_COLOR=0
    -DST7789_USE_DMA=1
    -DST7789_CS_ALWAYS_ACTIVE=0
    -DST7789_CS_ACTIVE_LOW=1
    -DST7789_COLOR_ORDER_BGR=0
    -DST7789_INVERT_DEFAULT=0
    -DX_SHIFT=0
    -DY_SHIFT=0
    -I.
    -Icore
    -Idevices
    -Iplatform
    -Istm32
    -Istm32/hw
    -Iplatform/mcp23017
    -Iui

build_src_filter =
    -<*>
    +<../stm32/*.c>
    +<../stm32/hw/*.c>
    +<../platform/mcp23017/*.c>
    +<../platform/dac8564/*.c>
    +<../platform/fram/*.c>
    +<../platform/midi/*.cpp>
    +<../core/*.cpp>
    +<../devices/sequencer/*.cpp>
    +<../devices/sequencer/chords/*.cpp>
    +<../ui/*.c>
    +<../stm32/sequencer_bridge.cpp>
    +<../stm32/user_chord_bridge.cpp>